export interface Product {
  id: number
  slug: string
  name: string
  category: string
  description: string
  shortDescription: string
  icon: string
}

export const categories = [
  "Beleza & Estetica",
  "Saude & Bem-estar",
  "Educacao",
  "Alimentacao",
  "Imoveis & Construcao",
  "Pets",
  "Automotivo",
  "Servicos Gerais",
  "Tecnologia & Marketing",
  "Moda & Acessorios",
  "Financeiro & Juridico",
  "Eventos & Entretenimento",
] as const

export const products: Product[] = [
  { id: 1, slug: "salao-de-beleza", name: "Salao de Beleza", category: "Beleza & Estetica", icon: "Scissors", shortDescription: "Programa de afiliados para indicacao de clientes", description: "Sistema completo para saloes de beleza com programa de afiliados para indicacao de clientes, agendamento online, gestao financeira e fidelizacao." },
  { id: 2, slug: "barbearia", name: "Barbearia", category: "Beleza & Estetica", icon: "Scissors", shortDescription: "Assinaturas para cortes com beneficio de indicacao", description: "Gerencie sua barbearia com sistema de assinaturas para cortes, programa de indicacao e controle total de agendamentos e faturamento." },
  { id: 3, slug: "pet-shop", name: "Pet Shop", category: "Pets", icon: "Heart", shortDescription: "Promocoes para banho/tosa por indicacao", description: "Sistema completo para pet shops com promocoes por indicacao, agendamento de banho e tosa, controle de estoque e gestao de clientes." },
  { id: 4, slug: "clinica-estetica", name: "Clinica de Estetica", category: "Beleza & Estetica", icon: "Sparkles", shortDescription: "Captacao de clientes para procedimentos", description: "Solucao para clinicas de estetica com captacao de clientes, agendamento de procedimentos, prontuarios e gestao financeira completa." },
  { id: 5, slug: "clinica-odontologica", name: "Clinica Odontologica", category: "Saude & Bem-estar", icon: "Smile", shortDescription: "Indicacao para limpezas e clareamentos", description: "Sistema para clinicas odontologicas com programa de indicacao, agendamento, prontuario digital e gestao de tratamentos." },
  { id: 6, slug: "fisioterapia-pilates", name: "Fisioterapia / Pilates", category: "Saude & Bem-estar", icon: "Activity", shortDescription: "Pacotes de captacao por indicacao", description: "Gestao completa para clinicas de fisioterapia e pilates com pacotes de captacao, agendamento de sessoes e acompanhamento de pacientes." },
  { id: 7, slug: "studio-pilates", name: "Studio de Pilates", category: "Saude & Bem-estar", icon: "Activity", shortDescription: "Sistema de aulas com indicacao", description: "Controle total do seu studio de pilates com sistema de aulas, programa de indicacao e gestao de alunos e planos." },
  { id: 8, slug: "academias-boutique", name: "Academias Boutique", category: "Saude & Bem-estar", icon: "Dumbbell", shortDescription: "Planos para atrair alunos locais", description: "Sistema para academias boutique com planos de captacao local, gestao de alunos, controle de acesso e acompanhamento de treinos." },
  { id: 9, slug: "personal-trainer", name: "Personal Trainer", category: "Saude & Bem-estar", icon: "Dumbbell", shortDescription: "Pacotes de clientes indicados por mensalidade", description: "Ferramenta completa para personal trainers com gestao de clientes, programa de indicacao mensal, treinos personalizados e agenda." },
  { id: 10, slug: "spa", name: "Spa", category: "Beleza & Estetica", icon: "Droplets", shortDescription: "Programa de indicacoes para tratamentos", description: "Sistema para spas com programa de indicacao, agendamento de tratamentos, pacotes e gestao completa de servicos." },
  { id: 11, slug: "clinica-emagrecimento", name: "Clinica de Emagrecimento", category: "Saude & Bem-estar", icon: "TrendingDown", shortDescription: "Captacao de pacientes", description: "Solucao para clinicas de emagrecimento com captacao de pacientes, acompanhamento nutricional e gestao de tratamentos." },
  { id: 12, slug: "esteticista-autonoma", name: "Esteticista Autonoma", category: "Beleza & Estetica", icon: "Sparkles", shortDescription: "Fluxo de clientes novos recorrentes", description: "Sistema para esteticistas autonomas com captacao recorrente de clientes, agendamento e gestao financeira pessoal." },
  { id: 13, slug: "manicure-pedicure", name: "Manicure / Pedicure", category: "Beleza & Estetica", icon: "Paintbrush", shortDescription: "Calendario de promocoes e indicacoes", description: "Gestao para profissionais de manicure e pedicure com calendario de promocoes, indicacao de clientes e agenda online." },
  { id: 14, slug: "micropigmentacao", name: "Micropigmentacao / Sobrancelhas", category: "Beleza & Estetica", icon: "Eye", shortDescription: "Campanhas para agendamentos", description: "Sistema para profissionais de micropigmentacao com campanhas de captacao, agendamento online e portfolio digital." },
  { id: 15, slug: "escola-idiomas", name: "Escola de Idiomas", category: "Educacao", icon: "BookOpen", shortDescription: "Inscricoes via indicacao", description: "Plataforma para escolas de idiomas com programa de indicacao para novas matriculas, gestao de turmas e acompanhamento de alunos." },
  { id: 16, slug: "escola-musica", name: "Escola de Musica", category: "Educacao", icon: "Music", shortDescription: "Captar novos alunos para aulas", description: "Sistema para escolas de musica com captacao de alunos, gestao de aulas, agendamento de instrumentos e acompanhamento pedagogico." },
  { id: 17, slug: "curso-reforco", name: "Curso de Reforco", category: "Educacao", icon: "GraduationCap", shortDescription: "Indicacao de alunos", description: "Plataforma para cursos de reforco escolar com programa de indicacao, gestao de aulas particulares e acompanhamento pedagogico." },
  { id: 18, slug: "buffet-infantil", name: "Buffet Infantil", category: "Eventos & Entretenimento", icon: "PartyPopper", shortDescription: "Leads para eventos", description: "Sistema para buffets infantis com captacao de leads, gestao de eventos, orcamentos automatizados e controle financeiro." },
  { id: 19, slug: "fotografo-eventos", name: "Fotografo de Eventos", category: "Eventos & Entretenimento", icon: "Camera", shortDescription: "Pacotes de indicacao", description: "Plataforma para fotografos com programa de indicacao, portfolio online, gestao de ensaios e entregas automatizadas." },
  { id: 20, slug: "buffet-casamentos", name: "Buffet / Cerimonial para Casamentos", category: "Eventos & Entretenimento", icon: "Heart", shortDescription: "Leads qualificados", description: "Sistema completo para buffets e cerimoniais de casamentos com captacao de leads qualificados, gestao de eventos e orcamentos." },
  { id: 21, slug: "loja-roupas", name: "Loja de Roupas Local", category: "Moda & Acessorios", icon: "Shirt", shortDescription: "Assinaturas de cupons para atrair clientes", description: "Sistema para lojas de roupas com programa de cupons por assinatura, fidelizacao de clientes e gestao de estoque." },
  { id: 22, slug: "boutique-noivas", name: "Boutique de Noivas", category: "Moda & Acessorios", icon: "Heart", shortDescription: "Visitas agendadas via indicacoes", description: "Plataforma para boutiques de noivas com agendamento de visitas, programa de indicacao e gestao de provas e ajustes." },
  { id: 23, slug: "roupas-infantis", name: "Roupas Infantis", category: "Moda & Acessorios", icon: "Baby", shortDescription: "Captacao via parcerias com maternidades", description: "Sistema para lojas de roupas infantis com parcerias estrategicas, programa de indicacao e gestao de estoque sazonal." },
  { id: 24, slug: "loja-sapatos", name: "Loja de Sapatos", category: "Moda & Acessorios", icon: "Footprints", shortDescription: "Promocoes recorrentes para novos clientes", description: "Plataforma para lojas de sapatos com promocoes recorrentes, programa de fidelidade e gestao de clientes e estoque." },
  { id: 25, slug: "moveis-planejados", name: "Moveis Planejados", category: "Imoveis & Construcao", icon: "Sofa", shortDescription: "Leads para orcamentos", description: "Sistema para lojas de moveis planejados com captacao de leads, gestao de projetos, orcamentos automatizados e acompanhamento de obras." },
  { id: 26, slug: "decoracao-arquitetos", name: "Decoracao / Arquitetos", category: "Imoveis & Construcao", icon: "Palette", shortDescription: "Captacao de clientes para projetos", description: "Plataforma para decoradores e arquitetos com captacao de clientes, portfolio digital, gestao de projetos e orcamentos." },
  { id: 27, slug: "construtora-reforma", name: "Construtora / Reforma", category: "Imoveis & Construcao", icon: "Hammer", shortDescription: "Leads para orcamentos", description: "Sistema para construtoras com captacao de leads, gestao de obras, orcamentos detalhados e acompanhamento de projetos." },
  { id: 28, slug: "imobiliaria", name: "Imobiliaria Local", category: "Imoveis & Construcao", icon: "Home", shortDescription: "Programa de indicacao para visitas", description: "Plataforma para imobiliarias com programa de indicacao, catalogo de imoveis, agendamento de visitas e gestao de corretores." },
  { id: 29, slug: "corretor-imoveis", name: "Corretor de Imoveis", category: "Imoveis & Construcao", icon: "Key", shortDescription: "Leads qualificados via assinatura", description: "Sistema para corretores autonomos com captacao de leads qualificados, gestao de carteira de imoveis e acompanhamento de vendas." },
  { id: 30, slug: "limpeza-residencial", name: "Limpeza Residencial", category: "Servicos Gerais", icon: "SprayCan", shortDescription: "Clientes recorrentes indicados", description: "Plataforma para servicos de limpeza com programa de indicacao, agendamento recorrente e gestao de equipes." },
  { id: 31, slug: "dedetizacao", name: "Dedetizacao", category: "Servicos Gerais", icon: "Bug", shortDescription: "Pacotes de captacao por regiao", description: "Sistema para empresas de dedetizacao com captacao por regiao, agendamento de visitas e gestao de servicos." },
  { id: 32, slug: "lavanderia", name: "Lavanderia / Self-service", category: "Servicos Gerais", icon: "Waves", shortDescription: "Assinaturas para captar clientes", description: "Plataforma para lavanderias com planos de assinatura, fidelizacao de clientes e gestao de pedidos e entregas." },
  { id: 33, slug: "car-wash", name: "Car Wash / Estetica Automotiva", category: "Automotivo", icon: "Car", shortDescription: "Clientes por indicacao", description: "Sistema para car wash com programa de indicacao, agendamento online, pacotes de servicos e fidelizacao de clientes." },
  { id: 34, slug: "oficina-mecanica", name: "Oficina Mecanica", category: "Automotivo", icon: "Wrench", shortDescription: "Leads para revisao e manutencao", description: "Plataforma para oficinas mecanicas com captacao de leads, historico de veiculos, orcamentos e gestao de servicos." },
  { id: 35, slug: "funilaria-pintura", name: "Funilaria / Pintura", category: "Automotivo", icon: "Paintbrush", shortDescription: "Captar orcamentos", description: "Sistema para funilarias com captacao de orcamentos, acompanhamento de servicos e gestao de pecas e materiais." },
  { id: 36, slug: "estetica-automotiva", name: "Estetica Automotiva", category: "Automotivo", icon: "Sparkles", shortDescription: "Agendamentos por indicacao", description: "Plataforma para estetica automotiva com programa de indicacao, agendamento de polimentos e gestao de pacotes premium." },
  { id: 37, slug: "pet-sitter", name: "Pet Sitter / Dog Walker", category: "Pets", icon: "Dog", shortDescription: "Clientes recorrentes indicados", description: "Sistema para pet sitters com programa de indicacao, agendamento de passeios, monitoramento e gestao de clientes." },
  { id: 38, slug: "creche-infantil", name: "Creche / Escolinha", category: "Educacao", icon: "Baby", shortDescription: "Matriculas por programa de indicacao", description: "Plataforma para creches e escolinhas com programa de indicacao para matriculas, comunicacao com pais e gestao pedagogica." },
  { id: 39, slug: "clinica-veterinaria", name: "Clinica Veterinaria", category: "Pets", icon: "Stethoscope", shortDescription: "Captacao para consultas e vacinas", description: "Sistema para clinicas veterinarias com captacao de pacientes, prontuario animal, agendamento e controle de vacinas." },
  { id: 40, slug: "laboratorio-exames", name: "Laboratorio de Exames", category: "Saude & Bem-estar", icon: "TestTube", shortDescription: "Marcacao de exames por indicacao", description: "Plataforma para laboratorios com programa de indicacao, agendamento de exames, resultados online e gestao de pacientes." },
  { id: 41, slug: "consultorio-psicologia", name: "Consultorio de Psicologia", category: "Saude & Bem-estar", icon: "Brain", shortDescription: "Captar pacientes particulares", description: "Sistema para psicologos com captacao de pacientes, agendamento de consultas, prontuario digital e gestao financeira." },
  { id: 42, slug: "coach-mentor", name: "Coach / Mentor de Carreira", category: "Educacao", icon: "Target", shortDescription: "Leads para sessoes individuais", description: "Plataforma para coaches com captacao de leads, agendamento de sessoes, acompanhamento de metas e gestao de programas." },
  { id: 43, slug: "consultoria-nutricional", name: "Consultoria Nutricional", category: "Saude & Bem-estar", icon: "Apple", shortDescription: "Pacotes de indicacao e retencao", description: "Sistema para nutricionistas com programa de indicacao, planos alimentares, acompanhamento de pacientes e gestao de consultas." },
  { id: 44, slug: "massoterapeuta", name: "Massoterapeuta", category: "Saude & Bem-estar", icon: "Hand", shortDescription: "Agendamentos via afiliados locais", description: "Plataforma para massoterapeutas com programa de afiliados, agendamento online e gestao de sessoes e pacotes." },
  { id: 45, slug: "cosmetologa-dermatologista", name: "Cosmetologa / Dermatologista", category: "Saude & Bem-estar", icon: "Sparkles", shortDescription: "Captacao de pacientes", description: "Sistema para dermatologistas com captacao de pacientes, prontuario digital, agendamento e acompanhamento de tratamentos." },
  { id: 46, slug: "loja-suplementos", name: "Loja de Suplementos", category: "Saude & Bem-estar", icon: "Pill", shortDescription: "Atrair clientes para compra recorrente", description: "Plataforma para lojas de suplementos com programa de compra recorrente, fidelizacao e gestao de estoque e vendas." },
  { id: 47, slug: "nutricionista-esportivo", name: "Nutricionista Esportivo", category: "Saude & Bem-estar", icon: "Dumbbell", shortDescription: "Captar atletas/clientes", description: "Sistema para nutricionistas esportivos com captacao de atletas, planos nutricionais, suplementacao e acompanhamento de resultados." },
  { id: 48, slug: "equipamentos-esportivos", name: "Equipamentos Esportivos", category: "Servicos Gerais", icon: "Trophy", shortDescription: "Promocoes locais", description: "Plataforma para lojas de equipamentos esportivos com promocoes locais, programa de indicacao e gestao de estoque." },
  { id: 49, slug: "estetica-capilar", name: "Estetica Capilar", category: "Beleza & Estetica", icon: "Scissors", shortDescription: "Tratamentos e cronograma de indicacao", description: "Sistema para clinicas de estetica capilar com cronograma de indicacao, tratamentos personalizados e gestao de clientes." },
  { id: 50, slug: "estudio-tatuagem", name: "Estudio de Tatuagem", category: "Beleza & Estetica", icon: "Pen", shortDescription: "Agendamento de clientes via promocoes", description: "Plataforma para estudios de tatuagem com agendamento online, portfolio digital, promocoes e gestao de agenda." },
  { id: 51, slug: "joalheria", name: "Joalheria Local", category: "Moda & Acessorios", icon: "Gem", shortDescription: "Leads para eventos e vendas de pecas", description: "Sistema para joalherias com captacao de leads, catalogo digital, gestao de eventos e acompanhamento de vendas." },
  { id: 52, slug: "agencia-viagens", name: "Agencia de Viagens", category: "Eventos & Entretenimento", icon: "Plane", shortDescription: "Pacotes por indicacao", description: "Plataforma para agencias de viagens com pacotes por indicacao, gestao de roteiros, reservas e acompanhamento de clientes." },
  { id: 53, slug: "agencia-intercambio", name: "Agencia de Intercambio", category: "Educacao", icon: "Globe", shortDescription: "Captar candidatos para programas", description: "Sistema para agencias de intercambio com captacao de candidatos, gestao de programas, documentacao e acompanhamento." },
  { id: 54, slug: "corretora-seguros", name: "Corretora de Seguros", category: "Financeiro & Juridico", icon: "Shield", shortDescription: "Leads qualificados via assinatura", description: "Plataforma para corretoras de seguros com captacao de leads, gestao de apolices, renovacoes e acompanhamento de sinistros." },
  { id: 55, slug: "escritorio-contabil", name: "Escritorio Contabil", category: "Financeiro & Juridico", icon: "Calculator", shortDescription: "Captar novos clientes PJ", description: "Sistema para escritorios contabeis com captacao de clientes PJ, gestao fiscal, obrigacoes e acompanhamento tributario." },
  { id: 56, slug: "escritorio-advocacia", name: "Escritorio de Advocacia", category: "Financeiro & Juridico", icon: "Scale", shortDescription: "Leads por regiao", description: "Plataforma para escritorios de advocacia com captacao de leads por regiao, gestao de processos e acompanhamento juridico." },
  { id: 57, slug: "delivery-local", name: "Servico de Delivery Local", category: "Alimentacao", icon: "Truck", shortDescription: "Assinaturas para restaurantes parceiros", description: "Sistema de delivery local com gestao de restaurantes parceiros, assinaturas, rastreamento de pedidos e fidelizacao." },
  { id: 58, slug: "restaurante-bar", name: "Restaurante / Bar", category: "Alimentacao", icon: "UtensilsCrossed", shortDescription: "Programas de fidelidade e indicacao", description: "Plataforma para restaurantes e bares com programa de fidelidade, indicacao de clientes, cardapio digital e gestao de mesas." },
  { id: 59, slug: "food-truck", name: "Food Truck", category: "Alimentacao", icon: "Truck", shortDescription: "Agendamentos para eventos/indicacoes", description: "Sistema para food trucks com agendamento de eventos, programa de indicacao, cardapio digital e gestao de locais." },
  { id: 60, slug: "loja-bebidas", name: "Loja de Bebidas / Adega", category: "Alimentacao", icon: "Wine", shortDescription: "Promocoes para novos clientes", description: "Plataforma para lojas de bebidas com promocoes para novos clientes, clube de vinhos, gestao de estoque e delivery." },
  { id: 61, slug: "confeitaria", name: "Confeitaria / Bolos Decorados", category: "Alimentacao", icon: "Cake", shortDescription: "Pedidos por indicacao", description: "Sistema para confeitarias com programa de indicacao, encomendas online, portfolio de bolos e gestao de producao." },
  { id: 62, slug: "pizzaria", name: "Pizzaria Local", category: "Alimentacao", icon: "Pizza", shortDescription: "Campanhas de recomendacao", description: "Plataforma para pizzarias com campanhas de recomendacao, cardapio digital, delivery integrado e fidelizacao de clientes." },
  { id: 63, slug: "catering-corporativo", name: "Catering Corporativo", category: "Alimentacao", icon: "Briefcase", shortDescription: "Leads para eventos empresariais", description: "Sistema para servicos de catering com captacao de leads corporativos, gestao de cardapios, orcamentos e logistica de eventos." },
  { id: 64, slug: "coworking", name: "Coworking Local", category: "Servicos Gerais", icon: "Building", shortDescription: "Captacao de membros e day passes", description: "Plataforma para coworkings com captacao de membros, day passes, gestao de espacos e reservas de salas." },
  { id: 65, slug: "escritorio-arquitetura", name: "Escritorio de Arquitetura", category: "Imoveis & Construcao", icon: "Ruler", shortDescription: "Novos projetos via indicacao", description: "Sistema para escritorios de arquitetura com captacao de projetos via indicacao, portfolio digital e gestao de obras." },
  { id: 66, slug: "designer-grafico", name: "Designer Grafico Freelance", category: "Tecnologia & Marketing", icon: "Palette", shortDescription: "Captar pequenos negocios locais", description: "Plataforma para designers freelancers com captacao de clientes locais, portfolio online e gestao de projetos." },
  { id: 67, slug: "agencia-marketing", name: "Agencia de Marketing Digital", category: "Tecnologia & Marketing", icon: "BarChart", shortDescription: "Leads para servicos", description: "Sistema para agencias de marketing com captacao de leads, gestao de campanhas, relatorios e acompanhamento de resultados." },
  { id: 68, slug: "produtora-video", name: "Produtora de Video", category: "Tecnologia & Marketing", icon: "Video", shortDescription: "Captar empresas para conteudo", description: "Plataforma para produtoras de video com captacao de clientes, gestao de producoes, entregas e portfolio digital." },
  { id: 69, slug: "produtor-audio", name: "Produtor de Audio / Podcast", category: "Tecnologia & Marketing", icon: "Headphones", shortDescription: "Captar clientes para producao", description: "Sistema para produtores de audio com captacao de clientes, gestao de gravacoes, edicao e distribuicao de conteudo." },
  { id: 70, slug: "eventos-corporativos", name: "Eventos Corporativos", category: "Eventos & Entretenimento", icon: "CalendarDays", shortDescription: "Leads e agendamentos", description: "Plataforma para organizadores de eventos corporativos com captacao de leads, gestao de agenda, orcamentos e logistica." },
  { id: 71, slug: "consultoria-rh", name: "Consultoria em RH", category: "Servicos Gerais", icon: "Users", shortDescription: "Leads para vagas e recrutamento", description: "Sistema para consultorias de RH com captacao de leads, gestao de vagas, processos seletivos e acompanhamento de contratacoes." },
  { id: 72, slug: "treinamentos-empresa", name: "Treinamentos In-company", category: "Educacao", icon: "Presentation", shortDescription: "Captar empresas locais", description: "Plataforma para treinamentos corporativos com captacao de empresas, gestao de cursos, instrutores e avaliacoes." },
  { id: 73, slug: "curso-online-empreendedores", name: "Curso Online para Empreendedores", category: "Educacao", icon: "Monitor", shortDescription: "Inscricoes via afiliados", description: "Sistema para cursos online com programa de afiliados, gestao de alunos, conteudos e certificacoes." },
  { id: 74, slug: "assessoria-imprensa", name: "Assessoria de Imprensa", category: "Tecnologia & Marketing", icon: "Newspaper", shortDescription: "Leads para clientes", description: "Plataforma para assessorias de imprensa com captacao de leads, gestao de releases, clipping e relacionamento com midia." },
  { id: 75, slug: "assessoria-politica", name: "Assessoria Politica / Consultoria", category: "Servicos Gerais", icon: "Megaphone", shortDescription: "Captar clientes", description: "Sistema para consultorias politicas com captacao de clientes, gestao de campanhas e acompanhamento estrategico." },
  { id: 76, slug: "barbershop-movel", name: "Barber/Shop Movel", category: "Beleza & Estetica", icon: "MapPin", shortDescription: "Agendamentos para eventos", description: "Plataforma para barbearias moveis com agendamento de eventos, roteirizacao, gestao de equipe e fidelizacao de clientes." },
  { id: 77, slug: "pilates-gestantes", name: "Pilates para Gestantes", category: "Saude & Bem-estar", icon: "Heart", shortDescription: "Captar novas alunas", description: "Sistema especializado para studios de pilates para gestantes com captacao de alunas, aulas e acompanhamento." },
  { id: 78, slug: "clinica-reproducao", name: "Clinica de Reproducao Assistida", category: "Saude & Bem-estar", icon: "HeartPulse", shortDescription: "Captacao de pacientes (alto ticket)", description: "Plataforma para clinicas de reproducao com captacao de pacientes qualificados, gestao de tratamentos e acompanhamento completo." },
  { id: 79, slug: "produtos-naturais", name: "Loja de Produtos Naturais", category: "Saude & Bem-estar", icon: "Leaf", shortDescription: "Clientes recorrentes por assinatura", description: "Sistema para lojas de produtos naturais com assinaturas recorrentes, fidelizacao e gestao de estoque organico." },
  { id: 80, slug: "foodbox-cestas", name: "Foodbox / Cestas Organicas", category: "Alimentacao", icon: "Package", shortDescription: "Entrega recorrente por indicacao", description: "Plataforma para servicos de cestas organicas com programa de indicacao, assinaturas recorrentes e logistica de entrega." },
  { id: 81, slug: "hortifruti-delivery", name: "Hortifruti Delivery", category: "Alimentacao", icon: "Truck", shortDescription: "Captar assinantes mensais", description: "Sistema para hortifrutis com delivery e assinatura mensal, gestao de pedidos, estoque e rotas de entrega." },
  { id: 82, slug: "jardinagem-paisagismo", name: "Jardinagem / Paisagismo", category: "Servicos Gerais", icon: "TreePine", shortDescription: "Orcamentos via indicacao", description: "Plataforma para servicos de jardinagem com captacao via indicacao, orcamentos automatizados e gestao de equipes." },
  { id: 83, slug: "paisagista-manutencao", name: "Paisagista / Manutencao", category: "Servicos Gerais", icon: "Flower", shortDescription: "Clientes recorrentes", description: "Sistema para paisagistas com programa de manutencao recorrente, captacao de clientes e gestao de projetos verdes." },
  { id: 84, slug: "servicos-mudanca", name: "Servicos de Mudanca", category: "Servicos Gerais", icon: "Truck", shortDescription: "Leads para orcamentos", description: "Plataforma para empresas de mudanca com captacao de leads, orcamentos online, agendamento e rastreamento." },
  { id: 85, slug: "montador-moveis", name: "Montador de Moveis / Marcenaria", category: "Servicos Gerais", icon: "Hammer", shortDescription: "Captar ordens de servico", description: "Sistema para montadores e marceneiros com captacao de ordens de servico, orcamentos e gestao de projetos." },
  { id: 86, slug: "conserto-eletrodomesticos", name: "Conserto de Eletrodomesticos", category: "Servicos Gerais", icon: "Wrench", shortDescription: "Atendimento e orcamentos", description: "Plataforma para servicos de conserto com captacao de clientes, orcamentos rapidos e gestao de assistencia tecnica." },
  { id: 87, slug: "curso-estetica-online", name: "Curso de Estetica Online", category: "Educacao", icon: "Monitor", shortDescription: "Alunos por programa de indicacao", description: "Sistema para cursos online de estetica com programa de indicacao, gestao de alunos, conteudos e certificacoes." },
  { id: 88, slug: "treinador-caes", name: "Treinador de Caes", category: "Pets", icon: "Dog", shortDescription: "Aulas e pacotes por indicacao", description: "Plataforma para treinadores de caes com programa de indicacao, pacotes de aulas, acompanhamento e gestao de alunos." },
  { id: 89, slug: "eventos-experiencias", name: "Eventos e Experiencias Locais", category: "Eventos & Entretenimento", icon: "Ticket", shortDescription: "Bilhetes por indicacao", description: "Sistema para eventos e experiencias locais com venda de bilhetes por indicacao, gestao de eventos e check-in digital." },
  { id: 90, slug: "brindes-personalizados", name: "Brindes Personalizados", category: "Servicos Gerais", icon: "Gift", shortDescription: "Captar empresas para brindes", description: "Plataforma para lojas de brindes com captacao de empresas, catalogo digital, orcamentos e gestao de producao." },
  { id: 91, slug: "fotografia-newborn", name: "Fotografia Newborn", category: "Eventos & Entretenimento", icon: "Camera", shortDescription: "Clientes por indicacao", description: "Sistema para fotografos newborn com programa de indicacao, portfolio, agendamento de ensaios e entregas digitais." },
  { id: 92, slug: "consultoria-financeira", name: "Consultoria Financeira Pessoal", category: "Financeiro & Juridico", icon: "Wallet", shortDescription: "Leads para planejamento", description: "Plataforma para consultores financeiros com captacao de leads, gestao de clientes, planejamento e acompanhamento de metas." },
  { id: 93, slug: "planejador-financeiro", name: "Planejador Financeiro PJ", category: "Financeiro & Juridico", icon: "BarChart", shortDescription: "Captar PJ", description: "Sistema para planejadores financeiros com captacao de empresas, gestao de carteira, relatorios e projecoes financeiras." },
  { id: 94, slug: "especialista-impostos", name: "Especialista em Impostos / MEI", category: "Financeiro & Juridico", icon: "FileText", shortDescription: "Captar microempreendedores", description: "Plataforma para especialistas em impostos com captacao de MEIs, gestao de declaracoes, obrigacoes e acompanhamento fiscal." },
  { id: 95, slug: "servicos-ti", name: "Servicos de TI Local", category: "Tecnologia & Marketing", icon: "Monitor", shortDescription: "Contratos mensais", description: "Sistema para empresas de TI com gestao de contratos mensais, tickets de suporte, manutencao e monitoramento de redes." },
  { id: 96, slug: "impressao-3d", name: "Impressao 3D Local", category: "Tecnologia & Marketing", icon: "Box", shortDescription: "Encomendas por indicacao", description: "Plataforma para servicos de impressao 3D com programa de indicacao, catalogo de produtos, orcamentos e gestao de pedidos." },
  { id: 97, slug: "cursos-presenciais", name: "Cursos Presenciais de Habilidades", category: "Educacao", icon: "ChefHat", shortDescription: "Alunos por programa", description: "Sistema para cursos presenciais como culinaria e costura com programa de indicacao, gestao de turmas e materiais." },
  { id: 98, slug: "escola-estetica", name: "Escola de Estetica / Cursos Tecnicos", category: "Educacao", icon: "GraduationCap", shortDescription: "Novos alunos via afiliados", description: "Plataforma para escolas de estetica com programa de afiliados, gestao de cursos, instrutores e certificacoes." },
  { id: 99, slug: "marketplace-servicos", name: "Marketplace Local de Servicos", category: "Tecnologia & Marketing", icon: "Store", shortDescription: "Assinaturas para prestadores", description: "Sistema marketplace para conectar prestadores de servicos locais com clientes, com planos de assinatura e avaliacoes." },
  { id: 100, slug: "plataforma-cupons", name: "Plataforma de Cupons Locais", category: "Tecnologia & Marketing", icon: "Ticket", shortDescription: "Assinaturas para comerciantes", description: "Plataforma de cupons para comerciantes locais com gestao de ofertas, captacao de clientes e analise de resultados." },
]

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category)
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase()
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      p.shortDescription.toLowerCase().includes(q)
  )
}
